### ISSUE TITLE
Missing/incorrect reports in .json feed for Mojolicious

### ISSUE THREAD

**Issue by stigtsp** [hackeriet/cpansa-feed#4]
From cpansa.json

```json
  "Mojolicious": [
    {
      "affected_versions": [
        "<0.991250"
      ],
      "cpansa_id": "CPANSA-MojoX-Dispatcher-Static-2009-5074",
      "cves": [
        "CVE-2009-5074"
      ],
      "description": "Unspecified vulnerability in the MojoX::Dispatcher::Static implementation in Mojolicious before 0.991250 has unknown impact and attack vectors.\n",
      "references": [
        "http://cpansearch.perl.org/src/KRAIH/Mojolicious-1.20/Changes"
      ],
      "reported": "2011-05-03",
      "severity": null
    }
  ]

```

This refers to MojoX-Dispatcher-Static and not Mojolicious

Doesn't result in expected output from `cpansa/CPANSA-Mojolicious.yml` which contains for instance:

```yaml

---
- id: CPANSA-Mojolicious-2022-03
  cves: []
  distribution: Mojolicious
  reported: 2022-12-10
  severity: ~
  description: >
    Mojo::DOM did not correctly parse <script> tags.
  affected_versions: "<9.31"
  fixed_versions: ">=9.31"
  references:
    - https://github.com/mojolicious/mojo/commit/6f195d85db6756022d3599f7d2634975688c9550
    - https://github.com/mojolicious/mojo/issues/2014
    - https://github.com/mojolicious/mojo/issues/2015
- id: CPANSA-Mojolicious-2021-02
  cves: []
  distribution: Mojolicious
  reported: 2021-06-01
  severity: ~
  description: >
    Small sessions could be used as part of a brute-force attack to decode the
    session secret.
  affected_versions: "<9.19"
  fixed_versions: ~
  references:
    - https://github.com/mojolicious/mojo/pull/1791
- id: CPANSA-Mojolicious-2021-01
  cves: []
  distribution: Mojolicious
  reported: 2021-03-16
  severity: ~
  description: >
    A bug in format detection can potentially be exploited for a DoS attack.
  affected_versions: "<9.11"
  fixed_versions: ~
  references:
    - https://github.com/mojolicious/mojo/issues/1736
    - https://github.com/mojolicious/mojo/commit/a0c4576ffb11c235088550de9ba7ac4196e1953c
- id: CPANSA-Mojolicious-2020-01
  cves: []
  distribution: Mojolicious
  reported: 2020-11-10
  severity: ~
  description: >
    Mojo::Util secure_compare can leak the string length.
    By immediately returning when the two strings are not the
    same length, the function allows an attacker to guess the
    length of the secret string using timing attacks.
  affected_versions: ">1.74,<8.65"
  fixed_versions: ~
  references:
    - https://github.com/mojolicious/mojo/pull/1601
  reviewed_by:
    - name: Robert Rothenberg
      email: rrwo@cpan.org
      date: 2022-06-22
[..]

```
